/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 139
#define YY_END_OF_BUFFER 140
static yyconst short int yy_acclist[466] =
    {   0,
       18,   18,   40,   40,  140,  138,  139,  137,  138,  139,
      137,  139,   91,  138,  139,    7,  138,  139,  112,  138,
      139,   92,  138,  139,   29,  138,  139,  132,  138,  139,
      133,  138,  139,  110,  138,  139,  108,  138,  139,  101,
      138,  139,  109,  138,  139,  126,  138,  139,  111,  138,
      139,  107,  138,  139,  128,  138,  139,  127,  138,  139,
      115,  138,  139,  119,  138,  139,  116,  138,  139,  129,
      138,  139,  138,  139,  136,  138,  139,   99,  138,  139,
      100,  138,  139,  136,  138,  139,  136,  138,  139,  136,
      138,  139,  136,  138,  139,  136,  138,  139,  136,  138,

      139,  136,  138,  139,  136,  138,  139,  136,  138,  139,
      136,  138,  139,  136,  138,  139,  136,  138,  139,  136,
      138,  139,  136,  138,  139,  136,  138,  139,  136,  138,
      139,  136,  138,  139,  134,  138,  139,   93,  138,  139,
      135,  138,  139,   94,  138,  139,    2,  139,    4,  139,
        3,  139,    8,  139,   15,  139,   23,  139,   18,  139,
       26,  139,   27,  139,   28,  139,   31,  139,   30,  139,
       40,  139,  137,  114,  124,   89,  122,  120,  121,    1,
        6,  123,  102,  106,  104,  103,  105,  131,  117,  113,
      118,  130,   24,  136,  136,  136,  136,  136,  136,  136,

      136,  136,  136,   73,  136,  136,  136,  136,  136,  136,
      136,   75,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  125,   90,    2,    3,    3,    5,    8,   21,   22,
       19,   20,   12,   13,   14,   10,   16,   11,   17,   26,
       25,   31,   43,   44,   41,   42,   35,   36,   37,   33,
       38,   34,   39,    6,  102,  102,  106,   95,   96,   97,
       98,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,   70,  136,  136,   46,
      136,  136,   67,  136,   50,  136,  136,  136,  136,  136,

       51,  136,  136,  136,  136,  136,  136,  136,  136,  136,
       47,  136,  136,  136,  136,    9,   32,   95,   96,   97,
       98,  136,   69,  136,   86,  136,  136,   78,  136,   45,
      136,  136,  136,  136,  136,  136,   76,  136,   61,  136,
      136,  136,  136,   82,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,   68,  136,   87,
      136,  136,  136,   48,  136,  136,    9,   32,  136,   80,
      136,   59,  136,  136,  136,  136,  136,   88,  136,   83,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,  136,   53,  136,  136,   72,  136,    9,

       32,  136,  136,  136,  136,   84,  136,  136,  136,  136,
      136,  136,  136,  136,   54,  136,   81,  136,   64,  136,
       60,  136,   49,  136,   58,  136,   77,  136,  136,    9,
       32,  136,  136,   85,  136,   79,  136,   71,  136,  136,
      136,  136,  136,   56,  136,  136,   65,  136,   63,  136,
       74,  136,  136,   57,  136,  136,   66,  136,  136,   62,
      136,   52,  136,   55,  136
    } ;

static yyconst short int yy_accept[322] =
    {   0,
        1,    1,    1,    1,    1,    2,    3,    3,    3,    4,
        5,    6,    8,   11,   13,   16,   19,   22,   25,   28,
       31,   34,   37,   40,   43,   46,   49,   52,   55,   58,
       61,   64,   67,   70,   73,   75,   78,   81,   84,   87,
       90,   93,   96,   99,  102,  105,  108,  111,  114,  117,
      120,  123,  126,  129,  132,  135,  138,  141,  144,  147,
      149,  151,  153,  155,  157,  159,  161,  163,  165,  167,
      169,  171,  173,  174,  175,  176,  177,  178,  179,  180,
      181,  182,  183,  184,  185,  186,  187,  188,  188,  189,
      190,  191,  192,  193,  194,  194,  195,  196,  197,  198,

      199,  200,  201,  202,  203,  204,  206,  207,  208,  209,
      210,  211,  212,  214,  215,  216,  217,  218,  219,  220,
      221,  222,  223,  224,  225,  226,  227,  228,  229,  230,
      231,  232,  233,  234,  235,  236,  237,  238,  239,  240,
      241,  242,  243,  244,  245,  246,  247,  248,  249,  250,
      250,  251,  252,  253,  254,  255,  256,  257,  258,  259,
      260,  261,  262,  263,  264,  264,  265,  266,  267,  268,
      272,  273,  274,  275,  276,  277,  278,  279,  280,  281,
      282,  283,  284,  285,  286,  287,  289,  290,  292,  293,
      295,  297,  298,  299,  300,  301,  303,  304,  305,  306,

      307,  308,  309,  310,  311,  313,  314,  315,  316,  317,
      318,  322,  323,  325,  327,  328,  330,  332,  333,  334,
      335,  336,  337,  339,  341,  342,  343,  344,  346,  347,
      348,  349,  350,  351,  352,  353,  354,  355,  356,  357,
      358,  360,  362,  363,  364,  366,  367,  368,  369,  370,
      372,  374,  375,  376,  377,  378,  380,  382,  383,  384,
      385,  386,  387,  388,  389,  390,  391,  392,  393,  394,
      395,  397,  398,  400,  401,  402,  403,  404,  405,  406,
      408,  409,  410,  411,  412,  413,  414,  415,  417,  419,
      421,  423,  425,  427,  429,  430,  431,  432,  433,  434,

      436,  438,  440,  441,  442,  443,  444,  446,  447,  449,
      451,  453,  454,  456,  457,  459,  460,  462,  464,  466,
      466
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   26,   26,   27,   26,   28,
       29,   29,   29,   29,   29,   29,   30,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       31,   32,   33,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   29,   44,   45,   46,   47,
       48,   49,   29,   50,   51,   52,   53,   54,   55,   56,
       29,   29,   57,   58,   59,   60,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[61] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        5,    1,    1,    1,    6,    1,    7,    7,    1,    1,
        1,    1,    1,    1,    1,    8,    8,    8,    9,    9,
        1,   10,    1,    9,    8,    8,    8,    8,    8,    8,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[342] =
    {   0,
        0,    0,   58,   59,   60,   61,   68,   69,   59,   67,
      648,  649,   74,   76,  625,  649,  624,  638,  649,  649,
      649,  622,  621,  649,  620,  649,   72,   85,  622,  649,
      618,  617,  616,  613,  631,  620,  649,  649,   53,   66,
       82,   70,   75,   91,   80,   93,   72,   81,   95,   65,
      114,  117,   90,  122,  129,  649,  116,  649,  649,    0,
      649,  131,    0,  649,  649,  170,    0,  649,  629,    0,
      649,  222,  147,  649,  649,  649,  649,  649,  649,  649,
        0,  649,  155,    0,  649,  649,  649,  134,  649,  649,
      649,  649,  649,  649,    0,  618,  128,  139,  140,  141,

      143,  146,  149,  145,  171,  147,  148,  161,  162,  181,
       71,  176,  617,  182,  189,  183,  188,  174,  194,  197,
      201,  208,  210,  203,  204,  206,  221,  200,  216,  234,
      236,  649,  649,    0,  245,  252,  649,    0,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  649,    0,
        0,  649,    0,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,    0,    0,  253,  649,  267,    0,
      237,  258,  250,  240,  267,  217,  271,  272,  273,  275,
      277,  279,  281,  283,  285,  287,  288,  289,  290,  616,
      615,  292,  293,  294,  296,  614,  297,  299,  300,  302,

      304,  306,  310,  315,  613,  308,  316,  318,    0,    0,
        0,  317,  612,  611,  320,  610,  609,  322,  323,  324,
      325,  336,  608,  607,  333,  328,  344,  606,  338,  343,
      346,  350,  353,  354,  356,  359,  360,  361,  362,  367,
      605,  604,  368,  369,  574,  371,    0,    0,  372,  567,
      556,  374,  376,  375,  378,  555,  547,  386,  385,  380,
      387,  390,  397,  398,  399,  400,  403,  404,  401,  409,
      546,  412,  536,    0,    0,  411,  413,  416,  418,  529,
      421,  422,  424,  429,  434,  426,  428,  526,  479,  475,
      474,  473,  470,  468,  437,  649,  649,  435,  439,  464,

      461,  460,  440,  441,  447,  452,  459,  453,  458,  445,
      233,  454,  229,  456,  131,  443,   83,   69,   67,  649,
      495,  505,  515,  525,  530,  539,  549,  559,  568,  578,
      587,  590,  593,  595,  597,  600,  602,  604,  606,  608,
      610
    } ;

static yyconst short int yy_def[342] =
    {   0,
      320,    1,  321,  321,  322,  322,  323,  323,  324,  324,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  325,  320,  320,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  320,  320,  320,  320,  326,
      320,  327,  328,  320,  320,  320,  329,  320,  320,  330,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      331,  320,  320,   28,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  332,  325,  325,  325,  325,  325,

      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  320,  320,  326,  327,  327,  320,  328,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  333,
      329,  320,  330,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  334,  331,  320,  320,  320,  335,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,

      325,  325,  325,  325,  325,  325,  325,  325,  336,  337,
      335,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  338,  339,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  340,  341,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  320,  320,  325,  325,  325,

      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,    0,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320
    } ;

static yyconst short int yy_nxt[710] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   36,   36,   36,   36,
       37,   12,   38,   36,   39,   40,   41,   42,   43,   44,
       45,   36,   46,   36,   36,   36,   47,   48,   49,   50,
       51,   52,   53,   54,   55,   36,   56,   57,   58,   59,
       61,   61,   64,   64,   65,   65,   71,   95,   62,   62,
       68,   68,   69,   69,   71,   73,   73,   73,   73,   95,
       95,   95,   80,   95,   95,   95,   95,   81,   97,   95,
       72,   66,   66,   82,   95,   95,   95,   95,   72,   83,

       98,   84,   84,  121,   95,   95,  115,   95,  105,   95,
      116,   85,   86,   99,   87,  100,  101,  106,   88,  107,
      186,  108,   85,  102,   86,  109,  103,  112,   95,  104,
       87,   95,  113,  117,  118,  110,   95,  132,  111,  114,
      127,  136,   95,   95,  119,   95,  137,  120,   73,   73,
      169,  169,  122,   95,   95,   95,  128,   95,  125,   95,
       95,   95,   95,   95,  129,  123,  126,   88,  124,  130,
      131,  167,  167,  133,  139,   95,   95,  140,  171,  174,
      176,  168,  168,  177,  168,   95,  141,  173,   95,  172,
       95,  178,  168,  175,  168,   95,   95,   95,  182,  181,

      168,  142,   95,   95,  143,  144,  184,  179,   95,  145,
      180,   95,  192,  183,   95,   95,  146,   95,   95,  147,
       95,  148,   95,  149,   95,  150,  154,  187,  185,  155,
       95,   95,  195,  188,  189,   95,  193,  190,  156,  191,
      196,  194,  198,   95,  199,  201,  202,   95,   95,  205,
       95,   95,  197,  157,   95,  320,  158,  159,  203,  200,
      320,  160,  136,  204,   95,  206,  217,  137,  161,  167,
      167,  162,   95,  163,  215,  164,  207,  165,  208,  168,
      168,   95,  168,  169,  169,   95,   95,   95,  212,   95,
      168,   95,  168,   95,  214,   95,  213,   95,  168,   95,

       88,   95,   95,   95,   95,  216,   95,   95,   95,  221,
       95,   95,  222,   95,   95,  220,   95,  223,   95,  226,
       95,  218,   95,  219,   95,  227,  224,  229,  230,   95,
       95,   95,   95,  225,   95,  228,   95,   95,   95,   95,
      234,  231,   95,  236,  238,  233,  232,   95,  242,  235,
       95,  237,   95,  245,  239,  240,  241,   95,   95,  244,
       95,  243,  246,  250,   95,  252,  249,   95,   95,  253,
       95,  256,  251,   95,   95,   95,   95,  254,  258,  257,
      255,   95,   95,   95,  262,   95,   95,  259,   95,   95,
       95,  263,   95,  260,   95,  261,  264,  266,  269,   95,

       95,   95,  267,  270,   95,  265,  276,  268,  271,  273,
      278,   95,   95,   95,   95,   95,  280,   95,   95,  279,
      277,  272,  281,   95,  282,   95,   95,   95,  284,  285,
       95,  283,   95,  287,  288,   95,   95,  290,   95,  291,
       95,  286,   95,   95,  292,  289,  295,  298,   95,   95,
      294,   95,  293,   95,   95,   95,  303,   95,  304,   95,
      300,   95,  302,  305,  307,  299,   95,   95,   95,  301,
       95,  306,   95,   95,   95,   95,  312,  311,   95,  308,
      319,  309,   95,  314,   95,  313,  310,   95,   95,   95,
      315,  316,  317,   95,  318,   60,   60,   60,   60,   60,

       60,   60,   60,   60,   60,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   96,   96,   96,   96,  134,
       95,  134,  134,   95,  134,  134,  134,  134,  134,  135,
       95,  135,  135,  135,  135,  135,  135,  135,  135,  138,
       95,   95,  138,  138,  138,  138,  138,  138,  151,   95,
       95,  151,  151,  151,  151,  151,  151,  151,  153,  153,
      153,   95,  153,  153,  153,  153,  153,  166,   95,  166,
      166,  166,  166,  166,  166,  166,  166,  170,  170,  209,

      209,  210,  210,  211,  211,  211,  247,  247,  248,  248,
      274,  274,  275,  275,  296,  296,  297,  297,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,  152,   95,   94,   93,   92,   91,   90,
       89,   79,   78,   77,   76,   75,   74,  320,   11,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  320
    } ;

static yyconst short int yy_chk[710] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    5,    6,    5,    6,    9,   39,    3,    4,
        7,    8,    7,    8,   10,   13,   13,   14,   14,   50,
       40,  319,   27,  318,   42,  111,   47,   27,   39,   43,
        9,    5,    6,   27,   45,   48,   41,  317,   10,   28,

       40,   28,   28,   50,   53,   44,   47,   46,   42,   49,
       47,   28,   28,   40,   28,   40,   41,   42,   28,   43,
      111,   43,   28,   41,   28,   44,   41,   45,   51,   41,
       28,   52,   46,   48,   48,   44,   54,   57,   44,   46,
       53,   62,   97,   55,   49,  315,   62,   49,   73,   73,
       88,   88,   51,   98,   99,  100,   54,  101,   52,  104,
      102,  106,  107,  103,   54,   51,   52,   88,   51,   54,
       55,   83,   83,   57,   66,  108,  109,   66,   97,  100,
      102,   83,   83,  103,   83,  105,   66,   99,  118,   98,
      112,  104,   83,  101,   83,  110,  114,  116,  107,  106,

       83,   66,  117,  115,   66,   66,  109,  105,  119,   66,
      105,  120,  118,  108,  128,  121,   66,  124,  125,   66,
      126,   66,  122,   66,  123,   66,   72,  112,  110,   72,
      129,  176,  120,  114,  115,  127,  119,  116,   72,  117,
      121,  119,  122,  313,  123,  124,  125,  311,  130,  128,
      131,  171,  121,   72,  174,  135,   72,   72,  126,  123,
      135,   72,  136,  127,  173,  129,  176,  136,   72,  167,
      167,   72,  172,   72,  174,   72,  130,   72,  131,  167,
      167,  175,  167,  169,  169,  177,  178,  179,  171,  180,
      167,  181,  167,  182,  173,  183,  172,  184,  167,  185,

      169,  186,  187,  188,  189,  175,  192,  193,  194,  180,
      195,  197,  181,  198,  199,  179,  200,  182,  201,  185,
      202,  177,  206,  178,  203,  186,  183,  188,  189,  204,
      207,  212,  208,  184,  215,  187,  218,  219,  220,  221,
      195,  192,  226,  198,  200,  194,  193,  225,  203,  197,
      222,  199,  229,  207,  200,  201,  202,  230,  227,  206,
      231,  204,  208,  215,  232,  219,  212,  233,  234,  220,
      235,  225,  218,  236,  237,  238,  239,  221,  227,  226,
      222,  240,  243,  244,  232,  246,  249,  229,  252,  254,
      253,  233,  255,  230,  260,  231,  234,  236,  239,  259,

      258,  261,  237,  240,  262,  235,  249,  238,  243,  246,
      253,  263,  264,  265,  266,  269,  255,  267,  268,  254,
      252,  244,  258,  270,  259,  276,  272,  277,  260,  261,
      278,  259,  279,  263,  264,  281,  282,  266,  283,  267,
      286,  262,  287,  284,  268,  265,  272,  276,  285,  298,
      270,  295,  269,  299,  303,  304,  282,  316,  283,  310,
      278,  305,  281,  284,  286,  277,  306,  308,  312,  279,
      314,  285,  309,  307,  302,  301,  303,  299,  300,  287,
      316,  295,  294,  305,  293,  304,  298,  292,  291,  290,
      306,  308,  312,  289,  314,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  325,  325,  325,  325,  326,
      288,  326,  326,  280,  326,  326,  326,  326,  326,  327,
      273,  327,  327,  327,  327,  327,  327,  327,  327,  328,
      271,  257,  328,  328,  328,  328,  328,  328,  329,  256,
      251,  329,  329,  329,  329,  329,  329,  329,  330,  330,
      330,  250,  330,  330,  330,  330,  330,  331,  245,  331,
      331,  331,  331,  331,  331,  331,  331,  332,  332,  333,

      333,  334,  334,  335,  335,  335,  336,  336,  337,  337,
      338,  338,  339,  339,  340,  340,  341,  341,  242,  241,
      228,  224,  223,  217,  216,  214,  213,  205,  196,  191,
      190,  113,   96,   69,   36,   35,   34,   33,   32,   31,
       29,   25,   23,   22,   18,   17,   15,   11,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  320
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "test.l"
#define INITIAL 0
#line 2 "test.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define MAX_STRING_LENGTH 1024
#define MAX_COMMENT_LENGTH 4096

char currentStringLiteral[MAX_STRING_LENGTH];
char currentComment[MAX_COMMENT_LENGTH];
char currentCharacter[10];
int currentInteger;
double currentFloatingPoint;
char buffer[10];
int currentStringIndex = 0;
int currentCommentIndex = 0;
int currentCharIndex = 0;

void print_token(const char* type, const char* value) {
    printf("%s: %s\n", type, value);
}

void print_token_simple(const char* type) {
    printf("%s\n", type);
}

void print_literal(const char* type, const char* text, double value) {
    printf("%s: %s -> %g\n", type, text, value);
}

void print_decimal_literal(const char* type, const char* text, double value) {
    printf("%s: %s -> %.15g\n", type, text, value);
}

void reset_string(char* str, int* index) {
    str[0] = '\0';
    *index = 0;
}

void append_char(char* str, int* index, char c) {
    if (*index < MAX_STRING_LENGTH - 1) {
        str[(*index)++] = c;
        str[*index] = '\0';
    }
}

void append_string(char* str, int* index, const char* src) {
    int len = strlen(src);
    if (*index + len < MAX_STRING_LENGTH - 1) {
        strcpy(str + *index, src);
        *index += len;
    }
}

void process_numeric_literal(const char* type, const char* text) {
    char cleaned[256];
    int j = 0;

    for (int i = 0; text[i] != '\0' && j < 255; i++) {
        if (text[i] != '_') {
            cleaned[j++] = text[i];
        }
    }
    cleaned[j] = '\0';
    
    char* endptr;
    long int_value = strtol(cleaned, &endptr, 10);
    printf("%s: %s -> %ld\n", type, text, int_value);
}

#define YY_NEVER_INTERACTIVE 1
#define MULTILINE_COMMENT 1

#define STRING_LITERAL 2

#define VERBATIM_STRING_LITERAL 3

#define CHARACTER_LITERAL 4

#line 776 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 89 "test.l"


#line 930 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 321 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 649 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 91 "test.l"
{
                                            reset_string(currentComment, &currentCommentIndex);
                                            BEGIN(MULTILINE_COMMENT);
                                        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 96 "test.l"
{ append_string(currentComment, &currentCommentIndex, yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 98 "test.l"
{ append_string(currentComment, &currentCommentIndex, yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 100 "test.l"
{ append_string(currentComment, &currentCommentIndex, yytext);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 102 "test.l"
{
                                            printf("MULTILINE_COMMENT: %s\n", currentComment);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 107 "test.l"
{
                                            printf("Error! Expected end of multiline comment but found end of file! Line: %d\n", yylineno);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 112 "test.l"
{ printf("Found single-line comment: %s\n", yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 114 "test.l"
{
                                            reset_string(currentStringLiteral, &currentStringIndex);
                                            BEGIN(STRING_LITERAL);
                                        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 119 "test.l"
{ append_string(currentStringLiteral, &currentStringIndex, yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 121 "test.l"
{
                                            memset(buffer, 0, sizeof(buffer));
                                            strncpy(buffer, yytext, yyleng);
                                            sscanf(buffer + 2, "%x", &currentInteger);
                                            append_char(currentStringLiteral, &currentStringIndex, (char)currentInteger);
                                        }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 128 "test.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\n');}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 130 "test.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\t');}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 132 "test.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\a');}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 134 "test.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\b');}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 136 "test.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\f');}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 138 "test.l"
{ printf("Error! Unterminated string literal at line: %d\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(STRING_LITERAL):
#line 140 "test.l"
{ printf("Error! Unterminated string literal at line: %d\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 142 "test.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\r');}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 144 "test.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\v');}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 146 "test.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\?');}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 148 "test.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\0');}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 150 "test.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\\');}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 152 "test.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\"');}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 154 "test.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\'');}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 156 "test.l"
{ printf("STRING_LITERAL: %s\n", currentStringLiteral); BEGIN(INITIAL);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 158 "test.l"
{ reset_string(currentStringLiteral, &currentStringIndex); BEGIN(VERBATIM_STRING_LITERAL); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 160 "test.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\"');}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 162 "test.l"
{ append_string(currentStringLiteral, &currentStringIndex, yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 164 "test.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\n');}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 166 "test.l"
{ printf("VERBATIM_STRING_LITERAL: %s\n", currentStringLiteral); BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(VERBATIM_STRING_LITERAL):
#line 168 "test.l"
{ printf("Error! Unterminated verbatim string literal at line: %d\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 170 "test.l"
{ reset_string(currentCharacter, &currentCharIndex); BEGIN(CHARACTER_LITERAL);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 172 "test.l"
{
                                            if (strlen(currentCharacter) == 0) 
                                            {
                                                printf("Error! Found empty character literal\n");
                                            }
                                            else if (strlen(currentCharacter) > 1)
                                            {
                                                printf("Error! Character literal is not allowed to have more than one character\n");
                                            }
                                            else 
                                            {
                                                printf("CHAR_LITERAL: %c\n", currentCharacter[0]);
                                            }
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 188 "test.l"
{ append_string(currentCharacter, &currentCharIndex, yytext);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 190 "test.l"
{
                                            memset(buffer, 0, sizeof(buffer));
                                            strncpy(buffer, yytext + 2, yyleng - 2);
                                            sscanf(buffer, "%x", &currentInteger);
                                            append_char(currentCharacter, &currentCharIndex, (char)currentInteger);
                                        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 197 "test.l"
{ append_char(currentCharacter, &currentCharIndex, '\n');}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 199 "test.l"
{ append_char(currentCharacter, &currentCharIndex, '\t');}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 201 "test.l"
{ append_char(currentCharacter, &currentCharIndex, '\a');}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 203 "test.l"
{ append_char(currentCharacter, &currentCharIndex, '\b');}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 205 "test.l"
{ append_char(currentCharacter, &currentCharIndex, '\f');}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 207 "test.l"
{ append_char(currentCharacter, &currentCharIndex, '\r');}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 209 "test.l"
{ append_char(currentCharacter, &currentCharIndex, '\v');}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 211 "test.l"
{ append_char(currentCharacter, &currentCharIndex, '\?');}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 213 "test.l"
{ append_char(currentCharacter, &currentCharIndex, '\0');}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 215 "test.l"
{ append_char(currentCharacter, &currentCharIndex, '\\');}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 217 "test.l"
{ append_char(currentCharacter, &currentCharIndex, '\"');}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 219 "test.l"
{ append_char(currentCharacter, &currentCharIndex, '\'');}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 223 "test.l"
{ printf("TYPE: %s\n", yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 224 "test.l"
{ printf("TYPE: %s\n", yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 225 "test.l"
{ printf("TYPE: %s\n", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 226 "test.l"
{ printf("TYPE: %s\n", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 227 "test.l"
{ printf("TYPE: %s\n", yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 230 "test.l"
{ printf("PARAMETER_MODIFIER: %s\n", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 231 "test.l"
{ printf("PARAMETER_MODIFIER: %s\n", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 234 "test.l"
{ printf("KEYWORD: %s\n", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 235 "test.l"
{ printf("KEYWORD: %s\n", yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 238 "test.l"
{ print_token("ACCESS_MODIFIER", yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 239 "test.l"
{ print_token("ACCESS_MODIFIER", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 240 "test.l"
{ print_token("ACCESS_MODIFIER", yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 241 "test.l"
{ print_token("ACCESS_MODIFIER", yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 243 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 244 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 245 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 246 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 247 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 248 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 249 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 250 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 251 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 252 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 253 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 254 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 256 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 257 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 258 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 259 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 260 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 261 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 262 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 263 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 264 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 265 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 266 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 267 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 268 "test.l"
{ print_token("KEYWORD", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 270 "test.l"
{ print_token("FLOAT_KEYWORD", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 271 "test.l"
{ print_token("DOUBLE_KEYWORD", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 272 "test.l"
{ print_token("DECIMAL_KEYWORD", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 273 "test.l"
{ print_token("BOOL_KEYWORD", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 274 "test.l"
{ print_token_simple("BOOL_LITERAL_TRUE"); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 275 "test.l"
{ print_token_simple("BOOL_LITERAL_FALSE"); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 277 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 278 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 279 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 280 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 281 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 282 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 284 "test.l"
{ print_token("CONSOLE_METHOD", yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 285 "test.l"
{ print_token("CONSOLE_METHOD", yytext); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 286 "test.l"
{ print_token("CONSOLE_METHOD", yytext); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 287 "test.l"
{ print_token("CONSOLE_METHOD", yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 289 "test.l"
{ print_token("LBRACKET", yytext); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 290 "test.l"
{ print_token("RBRACKET", yytext); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 291 "test.l"
{ print_token("COMMA", yytext); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 293 "test.l"
{
    char* endptr;
    char* input_text = strdup(yytext);
    int length = strlen(input_text);
    char last_char = input_text[length - 1];

    if (last_char == 'f' || last_char == 'F'){
        input_text[length - 1] = '\0';
        print_literal("FLOAT_LITERAL", yytext, strtof(input_text, &endptr));
    } else if (last_char == 'm' || last_char == 'M'){
        input_text[length - 1] = '\0';
        print_decimal_literal("DECIMAL_LITERAL", yytext, strtod(input_text, &endptr));
    } else if (last_char == 'd' || last_char == 'D'){
        input_text[length - 1] = '\0';
        print_literal("DOUBLE_LITERAL", yytext, strtod(input_text, &endptr));
    } else{
        print_literal("DOUBLE_LITERAL", yytext, strtod(input_text, &endptr));
    }
    free(input_text);
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 314 "test.l"
{
    char* endptr;
    char* input_text = strdup(yytext);
    input_text[strlen(input_text) - 1] = '\0';
    print_literal("FLOAT_LITERAL", yytext, strtof(input_text, &endptr));
    free(input_text); 
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 322 "test.l"
{ 
    char* endptr;
    char* input_text = strdup(yytext);
    input_text[strlen(input_text) - 1] = '\0';
    print_literal("DOUBLE_LITERAL", yytext, strtod(input_text, &endptr));
    free(input_text);
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 330 "test.l"
{ 
    char* endptr;
    char* input_text = strdup(yytext);
    input_text[strlen(input_text) - 1] = '\0';
    print_decimal_literal("DECIMAL_LITERAL", yytext, strtod(input_text, &endptr));
    free(input_text);
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 337 "test.l"
{ 
    process_numeric_literal("INTEGER_LITERAL", yytext);
}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 341 "test.l"
{ print_token("DIGIT", yytext); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 343 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 344 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 345 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 346 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 347 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 349 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 350 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 351 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 352 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 353 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 354 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 356 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 357 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 358 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 359 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 360 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 361 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 362 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 364 "test.l"
{ print_token("DOT", yytext); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 365 "test.l"
{ print_token("SEMICOLON", yytext); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 366 "test.l"
{ print_token("COLON", yytext); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 367 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 368 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 369 "test.l"
{ print_token("OPERATOR", yytext); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 370 "test.l"
{ print_token("LPAREN", yytext); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 371 "test.l"
{ print_token("RPAREN", yytext); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 372 "test.l"
{ print_token("LBRACE", yytext); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 373 "test.l"
{ print_token("RBRACE", yytext); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 375 "test.l"
{ print_token("IDENTIFIER", yytext); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 376 "test.l"
;
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 378 "test.l"
{ print_token("UNKNOWN_CHAR", yytext); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 380 "test.l"
ECHO;
	YY_BREAK
#line 1803 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(CHARACTER_LITERAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 321 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 321 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 320);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 380 "test.l"


int main() {
    printf("=== C# Lexer Started ===\n");
    yylex();
    printf("=== C# Lexer Finished ===\n");
    return 0;
}