/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 135
#define YY_END_OF_BUFFER 136
static yyconst short int yy_acclist[467] =
    {   0,
       41,   41,  136,  134,  135,  133,  134,  135,  133,  135,
       92,  134,  135,    8,  134,  135,  108,  134,  135,   93,
      134,  135,   30,  134,  135,  128,  134,  135,  129,  134,
      135,  106,  134,  135,  103,  134,  135,   98,  134,  135,
      105,  134,  135,  122,  134,  135,  107,  134,  135,  100,
      134,  135,  124,  134,  135,  123,  134,  135,  111,  134,
      135,  115,  134,  135,  112,  134,  135,  125,  134,  135,
      134,  135,  132,  134,  135,   96,  134,  135,   97,  134,
      135,  132,  134,  135,  132,  134,  135,  132,  134,  135,
      132,  134,  135,  132,  134,  135,  132,  134,  135,  132,

      134,  135,  132,  134,  135,  132,  134,  135,  132,  134,
      135,  132,  134,  135,  132,  134,  135,  132,  134,  135,
      132,  134,  135,  132,  134,  135,  132,  134,  135,  132,
      134,  135,  130,  134,  135,   94,  134,  135,  131,  134,
      135,   95,  134,  135,    2,  135,    5,  135,  135,    9,
      135,   16,  135,   23,  135,  135,   27,  135,   28,  135,
       29,  135,   32,  135,   31,  135,   41,  135,  133,  110,
      120,   90,  118,  102,  116,  104,  117,    1,    7,  119,
       99,  100,  127,  113,  109,  114,  126,   25,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,   74,  132,

      132,  132,  132,  132,  132,  132,   76,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  121,   91,    2,    3,
        4,    3,    6,    9,   24,   21,   24,   22,   24,   19,
       24,   20,   24,   13,   24,   14,   24,   15,   24,   11,
       24,   17,   24,   12,   24,   18,   24,   24,   27,   26,
       32,   44,   45,   42,   43,   36,   37,   38,   34,   39,
       35,   40,    7,   99,   99,  101,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,   71,  132,  132,   47,  132,  132,   68,  132,   51,

      132,  132,  132,  132,  132,   52,  132,  132,  132,  132,
      132,  132,  132,  132,  132,   50,  132,  132,  132,  132,
       10,   33,  132,   70,  132,   87,  132,  132,   79,  132,
       46,  132,  132,  132,  132,  132,  132,   77,  132,   62,
      132,  132,  132,  132,   83,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,   69,  132,
       88,  132,  132,  132,   48,  132,  132,   10,   33,  132,
       81,  132,   60,  132,  132,  132,  132,  132,   89,  132,
       84,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,   54,  132,  132,   73,  132,

       10,   33,  132,  132,  132,  132,   85,  132,  132,  132,
      132,  132,  132,  132,  132,   55,  132,   82,  132,   65,
      132,   61,  132,   49,  132,   59,  132,   78,  132,  132,
       10,   33,  132,  132,   86,  132,   80,  132,   72,  132,
      132,  132,  132,  132,   57,  132,  132,   66,  132,   64,
      132,   75,  132,  132,   58,  132,  132,   67,  132,  132,
       63,  132,   53,  132,   56,  132
    } ;

static yyconst short int yy_accept[321] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        3,    4,    6,    9,   11,   14,   17,   20,   23,   26,
       29,   32,   35,   38,   41,   44,   47,   50,   53,   56,
       59,   62,   65,   68,   71,   73,   76,   79,   82,   85,
       88,   91,   94,   97,  100,  103,  106,  109,  112,  115,
      118,  121,  124,  127,  130,  133,  136,  139,  142,  145,
      147,  149,  150,  152,  154,  156,  157,  159,  161,  163,
      165,  167,  169,  170,  171,  172,  173,  174,  175,  176,
      177,  178,  179,  180,  181,  182,  183,  183,  184,  185,
      186,  187,  188,  189,  190,  191,  192,  193,  194,  195,

      196,  197,  198,  199,  201,  202,  203,  204,  205,  206,
      207,  209,  210,  211,  212,  213,  214,  215,  216,  217,
      218,  219,  220,  221,  222,  223,  224,  225,  226,  227,
      228,  229,  230,  231,  232,  233,  234,  235,  236,  238,
      240,  242,  244,  246,  248,  250,  252,  254,  256,  258,
      259,  260,  261,  262,  263,  264,  265,  266,  267,  268,
      269,  270,  271,  272,  273,  273,  274,  275,  276,  277,
      278,  279,  280,  281,  282,  283,  284,  285,  286,  287,
      288,  289,  290,  291,  292,  294,  295,  297,  298,  300,
      302,  303,  304,  305,  306,  308,  309,  310,  311,  312,

      313,  314,  315,  316,  318,  319,  320,  321,  321,  322,
      323,  324,  326,  328,  329,  331,  333,  334,  335,  336,
      337,  338,  340,  342,  343,  344,  345,  347,  348,  349,
      350,  351,  352,  353,  354,  355,  356,  357,  358,  359,
      361,  363,  364,  365,  367,  368,  369,  370,  371,  373,
      375,  376,  377,  378,  379,  381,  383,  384,  385,  386,
      387,  388,  389,  390,  391,  392,  393,  394,  395,  396,
      398,  399,  401,  402,  403,  404,  405,  406,  407,  409,
      410,  411,  412,  413,  414,  415,  416,  418,  420,  422,
      424,  426,  428,  430,  431,  432,  433,  434,  435,  437,

      439,  441,  442,  443,  444,  445,  447,  448,  450,  452,
      454,  455,  457,  458,  460,  461,  463,  465,  467,  467
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   26,   26,   27,   26,   28,
       29,   29,   29,   29,   29,   29,   30,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       31,   32,   33,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   29,   44,   45,   46,   47,
       48,   49,   29,   50,   51,   52,   53,   54,   55,   56,
       29,   29,   57,   58,   59,   60,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[61] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        5,    1,    1,    1,    1,    1,    6,    6,    1,    1,
        1,    1,    1,    1,    1,    6,    6,    6,    7,    7,
        1,    8,    1,    7,    6,    6,    6,    6,    6,    6,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[340] =
    {   0,
        0,    0,   58,   59,   60,   61,   68,   69,   59,   67,
      430,  431,   74,   76,  407,  431,  406,  420,  431,  431,
      431,  404,   68,  431,   67,  431,   72,   67,  406,  431,
      402,  401,  400,  397,  415,    0,  431,  431,  383,   52,
       61,   47,   60,   63,  370,   57,   75,   59,   65,  378,
       77,   75,  365,   85,  373,  431,   97,  431,  431,    0,
      431,  119,    0,  431,  431,  151,    0,  431,  409,    0,
      431,  203,  121,  431,  431,  431,  431,  431,  431,  431,
      431,  431,    0,  431,  120,  127,  109,  431,  431,  431,
      431,  431,  431,    0,  362,  361,  363,  371,  358,  373,

      372,  359,   94,  352,  353,  350,  357,  353,  350,  347,
        0,  346,  351,  341,  343,  355,   93,  357,   99,  357,
      114,  348,  347,  336,  345,  337,  336,  342,  341,  431,
      431,    0,  431,  431,  151,  431,    0,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,    0,
        0,  431,    0,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,    0,    0,  154,  431,  135,  331,
      343,  336,  345,  340,  328,  326,  324,  332,  339,  337,
      333,  325,  319,  334,  329,  319,  327,  326,    0,    0,
      314,  309,  310,  316,    0,  307,  314,  306,  120,  305,

      305,  316,  307,    0,  301,  314,  306,  154,    0,    0,
      300,    0,    0,  305,    0,    0,  297,  298,  290,  274,
      281,    0,    0,  279,  260,  276,    0,  248,  244,  208,
      221,  215,  209,  201,  210,  205,  200,  209,  208,    0,
        0,  203,  189,    0,  202,    0,    0,  205,    0,    0,
      190,  201,  189,  194,    0,    0,  195,  138,  182,  187,
      177,  191,  190,  179,  187,  187,  182,  170,  179,    0,
      184,    0,    0,    0,  181,  164,  171,  163,    0,  172,
      178,  177,  175,  171,  167,  152,    0,    0,    0,    0,
        0,    0,    0,  157,  431,  431,  147,  158,    0,    0,

        0,  159,  150,  156,  151,    0,  150,    0,    0,    0,
      149,    0,  141,    0,  141,    0,    0,    0,  431,  259,
      267,  275,  283,  286,  293,  301,  309,  316,  324,  332,
      339,  171,  170,  169,  168,  140,  134,  115,   62
    } ;

static yyconst short int yy_def[340] =
    {   0,
      319,    1,  320,  320,  321,  321,  322,  322,  323,  323,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  324,  319,  319,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  319,  319,  319,  319,  325,
      319,  326,  327,  319,  319,  328,  329,  319,  319,  330,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  331,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  324,  324,  324,  324,  324,  324,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  319,
      319,  325,  319,  319,  319,  319,  327,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  332,
      329,  319,  330,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  333,  331,  319,  319,  319,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,

      324,  324,  324,  324,  324,  324,  324,  319,  334,  335,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  336,  337,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  338,  339,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  319,  319,  324,  324,  324,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,    0,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319
    } ;

static yyconst short int yy_nxt[492] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   36,   36,   36,   36,
       37,   12,   38,   36,   39,   40,   41,   42,   43,   44,
       45,   36,   46,   36,   36,   36,   47,   48,   49,   50,
       51,   52,   53,   54,   55,   36,   56,   57,   58,   59,
       61,   61,   64,   64,   65,   65,   71,  296,   62,   62,
       68,   68,   69,   69,   71,   73,   73,   73,   73,   78,
       80,   85,   82,   86,   86,  103,   96,   83,   81,   79,
       72,   66,   66,   84,  104,   99,  111,  107,   72,   97,

       87,   98,  100,  112,  105,  101,  106,  108,  102,  113,
      109,  115,  116,  114,  117,  120,  123,  118,  130,  126,
      295,  134,   73,   73,  124,  169,  169,  127,  121,  135,
      178,  122,  128,  179,  136,  192,  167,  167,  195,  274,
      193,   85,   87,   86,   86,  273,  168,  168,  198,  168,
      196,  169,  169,  134,  131,  139,  134,  168,  140,  168,
       87,  208,  237,  199,  208,  168,  136,  141,   87,  136,
      167,  167,  238,  247,  246,  210,  209,  281,  318,  317,
      168,  168,  142,  168,  282,  143,  144,  316,  315,  314,
      145,  168,  313,  168,  312,  311,  310,  146,  309,  168,

      147,  308,  148,  307,  149,  306,  150,  154,  305,  304,
      155,  303,  302,  301,  300,  299,  298,  297,  294,  156,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  280,  279,  278,  157,  277,  276,  158,  159,  275,
      272,  271,  160,  270,  269,  268,  267,  266,  265,  161,
      264,  263,  162,  262,  163,  261,  164,  260,  165,   60,
       60,   60,   60,   60,   60,   60,   60,   63,   63,   63,
       63,   63,   63,   63,   63,   67,   67,   67,   67,   67,
       67,   67,   67,   70,   70,   70,   70,   70,   70,   70,
       70,   94,   94,  132,  259,  132,  132,  258,  132,  132,

      132,  133,  133,  133,  133,  133,  133,  133,  133,  137,
      257,  256,  137,  137,  137,  137,  138,  255,  138,  138,
      138,  138,  138,  138,  151,  254,  253,  151,  151,  151,
      151,  151,  153,  153,  153,  252,  153,  153,  153,  166,
      251,  166,  166,  166,  166,  166,  166,  250,  249,  248,
      245,  244,  243,  242,  241,  240,  239,  236,  235,  234,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  207,  206,  205,  204,  203,  202,  201,
      200,  197,  194,  191,  190,  189,  188,  187,  186,  185,

      184,  183,  182,  181,  180,  177,  176,  175,  174,  173,
      172,  171,  170,  152,  129,  125,  119,  110,   95,   93,
       92,   91,   90,   89,   88,   77,   76,   75,   74,  319,
       11,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319

    } ;

static yyconst short int yy_chk[492] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    5,    6,    5,    6,    9,  339,    3,    4,
        7,    8,    7,    8,   10,   13,   13,   14,   14,   23,
       25,   28,   27,   28,   28,   42,   40,   27,   25,   23,
        9,    5,    6,   27,   42,   41,   46,   44,   10,   40,

       28,   40,   41,   46,   43,   41,   43,   44,   41,   47,
       44,   48,   48,   47,   49,   51,   52,   49,   57,   54,
      338,   62,   73,   73,   52,   87,   87,   54,   51,   62,
      103,   51,   54,  103,   62,  117,   85,   85,  119,  337,
      117,   86,   87,   86,   86,  336,   85,   85,  121,   85,
      119,  169,  169,  135,   57,   66,  208,   85,   66,   85,
       86,  135,  199,  121,  208,   85,  135,   66,  169,  208,
      167,  167,  199,  335,  334,  333,  332,  258,  315,  313,
      167,  167,   66,  167,  258,   66,   66,  311,  307,  305,
       66,  167,  304,  167,  303,  302,  298,   66,  297,  167,

       66,  294,   66,  286,   66,  285,   66,   72,  284,  283,
       72,  282,  281,  280,  278,  277,  276,  275,  271,   72,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  257,  254,  253,   72,  252,  251,   72,   72,  248,
      245,  243,   72,  242,  239,  238,  237,  236,  235,   72,
      234,  233,   72,  232,   72,  231,   72,  230,   72,  320,
      320,  320,  320,  320,  320,  320,  320,  321,  321,  321,
      321,  321,  321,  321,  321,  322,  322,  322,  322,  322,
      322,  322,  322,  323,  323,  323,  323,  323,  323,  323,
      323,  324,  324,  325,  229,  325,  325,  228,  325,  325,

      325,  326,  326,  326,  326,  326,  326,  326,  326,  327,
      226,  225,  327,  327,  327,  327,  328,  224,  328,  328,
      328,  328,  328,  328,  329,  221,  220,  329,  329,  329,
      329,  329,  330,  330,  330,  219,  330,  330,  330,  331,
      218,  331,  331,  331,  331,  331,  331,  217,  214,  211,
      207,  206,  205,  203,  202,  201,  200,  198,  197,  196,
      194,  193,  192,  191,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  174,  173,
      172,  171,  170,  129,  128,  127,  126,  125,  124,  123,
      122,  120,  118,  116,  115,  114,  113,  112,  110,  109,

      108,  107,  106,  105,  104,  102,  101,  100,   99,   98,
       97,   96,   95,   69,   55,   53,   50,   45,   39,   35,
       34,   33,   32,   31,   29,   22,   18,   17,   15,   11,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Lexer.l"
#define INITIAL 0
#line 2 "Lexer.l"
#include "Parser.tab.h" 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define MAX_STRING_LENGTH 1024
#define MAX_COMMENT_LENGTH 4096

void print_token(const char* type, const char* value) {
    printf("%s: %s\n", type, value);
}

void reset_string(char* str, int* index) {
    str[0] = '\0';
    *index = 0;
}

void append_char(char* str, int* index, char c) {
    if (*index < MAX_STRING_LENGTH - 1) {
        str[(*index)++] = c;
        str[*index] = '\0';
    }
}

void append_string(char* str, int* index, const char* src) {
    int len = strlen(src);
    if (*index + len < MAX_STRING_LENGTH - 1) {
        strcpy(str + *index, src);
        *index += len;
    }
}

#define YY_NEVER_INTERACTIVE 1
#define MULTILINE_COMMENT 1

#define STRING_LITERAL 2

#define VERBATIM_STRING_LITERAL 3

#define CHARACTER_LITERAL 4

#line 690 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 52 "Lexer.l"


char currentStringLiteral[MAX_STRING_LENGTH];
char currentComment[MAX_COMMENT_LENGTH];
char currentCharacter[10];
int currentInteger;
double currentFloatingPoint;
char buffer[10];
int currentStringIndex = 0;
int currentCommentIndex = 0;
int currentCharIndex = 0;
int last_was_string = 0;


#line 856 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 320 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 431 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 66 "Lexer.l"
{
                                            reset_string(currentComment, &currentCommentIndex);
                                            BEGIN(MULTILINE_COMMENT);
                                        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 71 "Lexer.l"
{append_string(currentComment, &currentCommentIndex, yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 73 "Lexer.l"
{append_string(currentComment, &currentCommentIndex, yytext);}
	YY_BREAK
case 4:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 75 "Lexer.l"
{append_string(currentComment, &currentCommentIndex, yytext);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 77 "Lexer.l"
{append_string(currentComment, &currentCommentIndex, yytext);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 79 "Lexer.l"
{
                                            printf("MULTILINE_COMMENT: %s\n", currentComment);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 84 "Lexer.l"
{
                                            printf("Error! Expected end of multiline comment but found end of file! Line: %d\n", yylineno);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 89 "Lexer.l"
{ printf("Found single-line comment: %s\n", yytext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 91 "Lexer.l"
{ 
    // Если предыдущий токен был STRING_LITERAL, игнорируем эту кавычку
    // Иначе начинаем новую строку
    last_was_string = 0;
    if (last_was_string) {
        last_was_string = 0;
        printf("DEBUG: Ignoring quote after string\n");
    } else {
        reset_string(currentStringLiteral, &currentStringIndex);
        BEGIN(STRING_LITERAL);
    }
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 104 "Lexer.l"
{ append_string(currentStringLiteral, &currentStringIndex, yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 106 "Lexer.l"
{
                                            memset(buffer, 0, sizeof(buffer));
                                            strncpy(buffer, yytext, yyleng);
                                            sscanf(buffer + 2, "%x", &currentInteger);
                                            append_char(currentStringLiteral, &currentStringIndex, (char)currentInteger);
                                        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 113 "Lexer.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\n');}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 115 "Lexer.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\t');}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 117 "Lexer.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\a');}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 119 "Lexer.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\b');}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 121 "Lexer.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\f');}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 123 "Lexer.l"
{ printf("Error! Unterminated string literal at line: %d\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(STRING_LITERAL):
#line 125 "Lexer.l"
{ printf("Error! Unterminated string literal at line: %d\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 127 "Lexer.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\r');}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 129 "Lexer.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\v');}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 131 "Lexer.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\0');}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 133 "Lexer.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\\');}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 135 "Lexer.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\"');}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 137 "Lexer.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\'');}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 139 "Lexer.l"
{
    yylval.string_value = strdup(currentStringLiteral);
    printf("DEBUG LEXER: Found string literal: '%s'\n", currentStringLiteral);
    last_was_string = 1;  // Помечаем что был строковый литерал
    BEGIN(INITIAL);
    return STRING_LITERAL;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 147 "Lexer.l"
{ printf("Error escape sequence in string: %s\n", currentStringLiteral);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 149 "Lexer.l"
{ reset_string(currentStringLiteral, &currentStringIndex); BEGIN(VERBATIM_STRING_LITERAL); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 151 "Lexer.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\"');}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 153 "Lexer.l"
{ append_string(currentStringLiteral, &currentStringIndex, yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 155 "Lexer.l"
{ append_char(currentStringLiteral, &currentStringIndex, '\n');}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 157 "Lexer.l"
{ 
    yylval.string_value = strdup(currentStringLiteral);
    BEGIN(INITIAL);
    return STRING_LITERAL;
}
	YY_BREAK
case YY_STATE_EOF(VERBATIM_STRING_LITERAL):
#line 163 "Lexer.l"
{ printf("Error! Unterminated verbatim string literal at line: %d\n", yylineno); BEGIN(INITIAL);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 165 "Lexer.l"
{ reset_string(currentCharacter, &currentCharIndex); BEGIN(CHARACTER_LITERAL);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 167 "Lexer.l"
{
                                            if (strlen(currentCharacter) == 0) 
                                            {
                                                printf("Error! Found empty character literal\n");
                                            }
                                            else if (strlen(currentCharacter) > 1)
                                            {
                                                printf("Error! Character literal is not allowed to have more than one character\n");
                                            }
    					    else {
						yylval.char_value = currentCharacter[0];
        					BEGIN(INITIAL);
        					return CHAR_LITERAL;
    					    }
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 184 "Lexer.l"
{ append_string(currentCharacter, &currentCharIndex, yytext);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 186 "Lexer.l"
{
                                            memset(buffer, 0, sizeof(buffer));
                                            strncpy(buffer, yytext + 2, yyleng - 2);
                                            sscanf(buffer, "%x", &currentInteger);
                                            append_char(currentCharacter, &currentCharIndex, (char)currentInteger);
                                        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 193 "Lexer.l"
{ append_char(currentCharacter, &currentCharIndex, '\n');}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 195 "Lexer.l"
{ append_char(currentCharacter, &currentCharIndex, '\t');}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 197 "Lexer.l"
{ append_char(currentCharacter, &currentCharIndex, '\a');}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 199 "Lexer.l"
{ append_char(currentCharacter, &currentCharIndex, '\b');}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 201 "Lexer.l"
{ append_char(currentCharacter, &currentCharIndex, '\f');}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 203 "Lexer.l"
{ append_char(currentCharacter, &currentCharIndex, '\r');}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 205 "Lexer.l"
{ append_char(currentCharacter, &currentCharIndex, '\v');}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 207 "Lexer.l"
{ append_char(currentCharacter, &currentCharIndex, '\?');}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 209 "Lexer.l"
{ append_char(currentCharacter, &currentCharIndex, '\0');}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 211 "Lexer.l"
{ append_char(currentCharacter, &currentCharIndex, '\\');}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 213 "Lexer.l"
{ append_char(currentCharacter, &currentCharIndex, '\"');}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 215 "Lexer.l"
{ append_char(currentCharacter, &currentCharIndex, '\'');}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 219 "Lexer.l"
{ return CHAR_TYPE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 220 "Lexer.l"
{ return INT_TYPE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 221 "Lexer.l"
{ return VOID_TYPE;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 222 "Lexer.l"
{ return STRING_TYPE;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 223 "Lexer.l"
{ return VAR_TYPE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 225 "Lexer.l"
{ return OUT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 226 "Lexer.l"
{ return REF;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 229 "Lexer.l"
{ return NAMESPACE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 230 "Lexer.l"
{ return USING; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 233 "Lexer.l"
{ return PUBLIC; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 234 "Lexer.l"
{ return PROTECTED; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 235 "Lexer.l"
{ return PRIVATE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 236 "Lexer.l"
{ return INTERNAL;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 238 "Lexer.l"
{ return STRUCT;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 239 "Lexer.l"
{ return CLASS;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 240 "Lexer.l"
{ return STATIC;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 241 "Lexer.l"
{ return ENUM; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 242 "Lexer.l"
{ return INTERFACE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 243 "Lexer.l"
{ return ABSTRACT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 244 "Lexer.l"
{ return SEALED; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 245 "Lexer.l"
{ return VIRTUAL;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 246 "Lexer.l"
{ return OVERRIDE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 247 "Lexer.l"
{ return NEW; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 248 "Lexer.l"
{ return THIS; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 249 "Lexer.l"
{ return BASE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 251 "Lexer.l"
{ return FOR; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 252 "Lexer.l"
{ return FOREACH; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 253 "Lexer.l"
{ return WHILE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 254 "Lexer.l"
{ return DO; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 255 "Lexer.l"
{ return CONTINUE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 256 "Lexer.l"
{ return IF; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 257 "Lexer.l"
{ return ELSE; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 258 "Lexer.l"
{ return SWITCH; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 259 "Lexer.l"
{ return CASE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 260 "Lexer.l"
{ return DEFAULT; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 261 "Lexer.l"
{ return BREAK; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 262 "Lexer.l"
{ return RETURN; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 263 "Lexer.l"
{ return GOTO; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 265 "Lexer.l"
{ return FLOAT_TYPE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 266 "Lexer.l"
{ return DOUBLE_TYPE; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 267 "Lexer.l"
{ return DECIMAL_TYPE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 268 "Lexer.l"
{ return BOOL_TYPE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 269 "Lexer.l"
{ yylval.bool_value = 1; return BOOL_LITERAL_TRUE; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 270 "Lexer.l"
{ yylval.bool_value = 0; return BOOL_LITERAL_FALSE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 272 "Lexer.l"
{ return AND; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 273 "Lexer.l"
{ return OR; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 274 "Lexer.l"
{ return '!'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 275 "Lexer.l"
{ return '&'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 276 "Lexer.l"
{ return '|'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 277 "Lexer.l"
{ return '~'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 279 "Lexer.l"
{ return '['; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 280 "Lexer.l"
{ return ']'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 281 "Lexer.l"
{ return ','; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 284 "Lexer.l"
{
    char* input_text = strdup(yytext);
    int length = strlen(input_text);
    char last_char = input_text[length - 1];

    if (last_char == 'f' || last_char == 'F'){
        input_text[length - 1] = '\0';
        yylval.float_value = strtof(input_text, NULL);
        free(input_text);
        return FLOAT_LITERAL;
    } else if (last_char == 'm' || last_char == 'M'){
        input_text[length - 1] = '\0';
        yylval.double_value = strtod(input_text, NULL);
        free(input_text);
        return DECIMAL_LITERAL;
    } else {
        yylval.double_value = strtod(input_text, NULL);
        free(input_text);
        return DOUBLE_LITERAL;
    }
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 308 "Lexer.l"
{
    yylval.int_value = atoi(yytext); 
    return INTEGER_LITERAL;
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 313 "Lexer.l"
{
    char cleaned[256];
    int j = 0;
    for (int i = 0; yytext[i] != '\0' && j < 255; i++) {
        if (yytext[i] != '_') cleaned[j++] = yytext[i];
    }
    cleaned[j] = '\0';
    yylval.int_value = atoi(cleaned); 
    return INTEGER_LITERAL;
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 324 "Lexer.l"
{ return PLUSPLUS; }  
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 325 "Lexer.l"
{ return '+'; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 326 "Lexer.l"
{ return MINUSMINUS; }  
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 327 "Lexer.l"
{ return '-'; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 328 "Lexer.l"
{ return '*'; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 329 "Lexer.l"
{ return '/'; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 330 "Lexer.l"
{ return '%'; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 332 "Lexer.l"
{ return EQUAL; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 333 "Lexer.l"
{ return NOT_EQUAL; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 334 "Lexer.l"
{ return '<'; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 335 "Lexer.l"
{ return '>'; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 336 "Lexer.l"
{ return LESS_EQUAL; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 337 "Lexer.l"
{ return GREATER_EQUAL; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 339 "Lexer.l"
{ return '='; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 340 "Lexer.l"
{ return PLUS_ASSIGNMENT; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 341 "Lexer.l"
{ return MINUS_ASSIGNMENT; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 342 "Lexer.l"
{ return MUL_ASSIGNMENT; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 343 "Lexer.l"
{ return DIV_ASSIGNMENT; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 344 "Lexer.l"
{ return MOD_ASSIGNMENT; }  
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 345 "Lexer.l"
{ return OR_ASSIGNMENT; }   
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 348 "Lexer.l"
{ return '.'; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 349 "Lexer.l"
{ return ';'; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 350 "Lexer.l"
{ return ':'; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 351 "Lexer.l"
{ return '?'; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 352 "Lexer.l"
{ return NULL_COALESCE; }   
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 353 "Lexer.l"
{ return SCOPE; }  
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 354 "Lexer.l"
{ return '('; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 355 "Lexer.l"
{ return ')'; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 356 "Lexer.l"
{ return '{'; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 357 "Lexer.l"
{ return '}'; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 359 "Lexer.l"
{ yylval.string_value = strdup(yytext); return IDENTIFIER; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 360 "Lexer.l"
;
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 362 "Lexer.l"
{ print_token("UNKNOWN_CHAR", yytext); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 364 "Lexer.l"
ECHO;
	YY_BREAK
#line 1724 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(CHARACTER_LITERAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 320 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 320 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 319);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 364 "Lexer.l"
